<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBdXSAO2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBdXSAO2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBdXSAO2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBdXSAO2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBdXSAO2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BdXSAO2',
    'container.build_id' => 'a9439495',
    'container.build_time' => 1626109782,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBdXSAO2');
